apiVersion: apps/v1
kind: Deployment

metadata:
  name: snowflake-operator

spec:
  template:
    metadata:
      labels:
        environment: dev

    spec:
      containers:
        - name: operator
          image: 752192503262.dkr.ecr.us-east-2.amazonaws.com/snowflake-operator:1.0.1-dev