apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snowflake-operator
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - snowflake-system

  selector:
    matchLabels:
      app: snowflake-operator

  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s